version: '3'

services:

  restaurant_web:
    container_name: restaurant_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/RestaurantPlatform/manage.py makemigrations &&
        python /usr/src/RestaurantPlatform/manage.py migrate --noinput &&
        python /usr/src/RestaurantPlatform/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/RestaurantPlatform
    ports:
      - "8000:8000"
