version: '3'

services:

  sj_web:
    container_name: sj_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/sj_project/manage.py makemigrations &&
        python /usr/src/sj_project/manage.py migrate --noinput &&
        python /usr/src/sj_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/sj_project
    ports:
      - "8000:8000"
